// Risk views: market deep-dive (ladder, map, liquidity, stress, ADL, funding, positions), validation and about.
import { h, s, fmt, num, view, API, app, colors, chartWidth, columnChart, lineChart, sparkline, legend, tableView, card, cardWithActions, tile, statusPill, table, getJson, seriesOf } from '../ui.js';

export function syncingView(data) {
  return h('div', {}, h('h1', {}, 'Collector is syncing'), h('p', { class: 'sub' }, 'The first pinned-block snapshot is being read from the exchange contract. This page refreshes automatically.'), data?.snapshot?.status_reason ? h('p', { class: 'notice' }, `Reason: ${data.snapshot.status_reason}`) : null);
}

export function liquidityCards(m) {
  const c = colors(), L = m.liquidity;
  if (!L) return [card('On-chain liquidity vs liquidation demand', null, h('div', { class: 'empty' }, 'Order-book depth has not been read yet'))];
  const rows = L.absorption;
  const chartFor = side => columnChart({ width: chartWidth(2), categories: rows.map(r => `${r.shock_pct}%`), series: [{ name: side === 'long' ? 'Long liquidations (sell demand)' : 'Short liquidations (buy demand)', color: side === 'long' ? c.long : c.short, values: rows.map(r => num(r[side].demand)) }, { name: side === 'long' ? 'Resting bid depth' : 'Resting ask depth', color: c.blue, values: rows.map(r => num(r[side].depth)) }], formatValue: (v, axis) => axis ? fmt.usd(v, 0) : fmt.usdFull(v), tooltipRows: i => [{ color: side === 'long' ? c.long : c.short, name: 'Liquidation demand', value: fmt.usdFull(rows[i][side].demand) }, { color: c.blue, name: `Depth (${rows[i][side].levels} levels)`, value: fmt.usdFull(rows[i][side].depth) }, { name: 'Cover', value: fmt.cover(rows[i][side].cover_pct) }] });
  const note = `Book read at block ${fmt.int(L.book_block)} (${fmt.int(L.age_blocks)} blocks ago) · spread ${L.spread_bps === null ? '—' : `${L.spread_bps} bps`} · ${L.levels.bids} bid / ${L.levels.asks} ask levels${L.truncated.bids || L.truncated.asks ? ' · walk truncated at the level limit' : ''}.`;
  const tbl = side => tableView('Show data table', ['Move', 'Demand', 'Depth', 'Levels', 'Cover'], rows.map(r => [`${r.shock_pct}%`, fmt.usdFull(r[side].demand), fmt.usdFull(r[side].depth), String(r[side].levels), fmt.cover(r[side].cover_pct)]));
  return [
    card('Long liquidations vs bid depth', note, legend([{ name: 'Long liquidations (sell demand)', color: c.long }, { name: 'Resting bid depth', color: c.blue }]), chartFor('long'), tbl('long')),
    card('Short liquidations vs ask depth', 'Firm resting orders only; expired volume awaiting clearing is excluded.', legend([{ name: 'Short liquidations (buy demand)', color: c.short }, { name: 'Resting ask depth', color: c.blue }]), chartFor('short'), tbl('short'))];
}

export function stressCard(m) {
  const container = h('div', { class: 'stress' });
  const value = h('span', { class: 'stress-value' }, fmt.signedPct(view.stressMove, 1));
  const results = h('div', {});
  const input = h('input', { type: 'range', min: '-30', max: '30', step: '0.5', value: String(view.stressMove), 'aria-label': 'Price move percent', oninput: evt => { view.stressMove = Number(evt.target.value); value.textContent = fmt.signedPct(view.stressMove, 1); clearTimeout(view.stressTimer); view.stressTimer = setTimeout(() => loadStress(m.id, results), 200); } });
  container.append(h('div', { class: 'stress-row' }, h('span', {}, 'Price move'), input, value, h('span', { style: 'color:var(--muted);font-size:12px' }, 'negative liquidates longs, positive liquidates shorts')), results);
  renderStress(results, m, view.stressResult && view.stressResult.market_id === m.id ? view.stressResult : null);
  if (!view.stressResult || view.stressResult.market_id !== m.id) loadStress(m.id, results);
  return card('Stress test', 'What liquidates if the mark moves by the chosen amount before any liquidation executes: notional, bad debt, insurance cover and the on-chain depth that would absorb the flow.', container);
}
export async function loadStress(marketId, target) {
  if (view.stressMove === 0) { renderStress(target, { id: marketId }, null); return; }
  const r = await getJson(`/markets/${marketId}/stress?move_pct=${view.stressMove}`);
  if (r.ok) { view.stressResult = r.data; if (view.route === 'market' && Number(view.params.id) === marketId) renderStress(target, { id: marketId, price_decimals: r.data.price_decimals }, r.data); }
}
export function renderStress(target, m, r) {
  if (!r) { target.replaceChildren(h('div', { class: 'empty' }, view.stressMove === 0 ? 'Choose a non-zero move' : 'Computing…')); return; }
  const pd = m.price_decimals ?? 2;
  target.replaceChildren(
    h('div', { class: 'stress-tiles' },
      tile(`Price after ${fmt.signedPct(r.move_pct, 1)}`, fmt.price(r.price, pd), `from ${fmt.price(r.mark, pd)}`),
      tile(`${r.side === 'long' ? 'Longs' : 'Shorts'} liquidated`, fmt.usd(r.liquidated.notional), `${r.liquidated.count} positions · ${fmt.pct(r.liquidated.share_of_oi_pct, 1)} of open interest`),
      tile('Bad debt if gapped', fmt.usd(r.shortfall), r.insurance_coverage_pct === null ? 'no position past bankruptcy' : `insurance covers ${fmt.cover(r.insurance_coverage_pct)}`, r.insurance_coverage_pct === null || r.insurance_coverage_pct >= 100 ? 'good' : 'critical'),
      tile('On-chain depth in range', r.liquidity ? fmt.usd(r.liquidity.depth) : '—', r.liquidity ? `${r.liquidity.levels} levels · covers ${fmt.cover(r.liquidity.absorption_pct)} of the flow` : 'book not read', r.liquidity && r.liquidity.absorption_pct !== null && r.liquidity.absorption_pct < 100 ? 'critical' : null)),
    r.positions_hit.length ? h('div', { style: 'margin-top:10px' }, h('h3', {}, 'Largest positions hit'), table(['Account', 'Side', 'Size', 'Notional', 'Entry', 'Liq. price', 'Leverage'], r.positions_hit.slice(0, 10).map(p => h('tr', {}, h('td', { class: 'left mono' }, h('a', { href: `#/account/${p.account_id}` }, `#${p.account_id}`)), h('td', { class: 'left' }, h('span', { class: `side-${p.side}` }, p.side)), h('td', {}, fmt.size(p.size)), h('td', {}, fmt.usd(p.notional)), h('td', {}, fmt.price(p.entry_price, pd)), h('td', {}, fmt.price(p.liquidation_price, pd)), h('td', {}, fmt.lev(p.leverage)))), 2)) : null);
}

export function adlCard(m) {
  const q = m.adl_queue;
  const rows = list => list.length ? table(['#', 'Account', 'Return on deposit', 'PnL', 'Notional', 'Leverage'], list.map(p => h('tr', {}, h('td', { class: 'left' }, String(p.rank)), h('td', { class: 'left mono' }, h('a', { href: `#/account/${p.account_id}` }, `#${p.account_id}`)), h('td', {}, fmt.pct(p.roe_pct, 1)), h('td', { class: 'status-ok' }, fmt.usd(p.pnl)), h('td', {}, fmt.usd(p.notional)), h('td', {}, fmt.lev(p.leverage)))), 2) : h('div', { class: 'empty' }, 'No profitable positions on this side');
  return card('Auto-deleveraging queue', q.method, h('div', { class: 'grid', style: 'margin-bottom:0' }, h('div', {}, h('h3', {}, 'Longs deleveraged first if shorts go bankrupt'), rows(q.long)), h('div', {}, h('h3', {}, 'Shorts deleveraged first if longs go bankrupt'), rows(q.short))));
}

export function marketView(m, markets, series) {
  const c = colors();
  const nav = h('div', { class: 'market-nav' }, markets.map(x => h('a', { href: `#/market/${x.id}`, class: [x.id === m.id ? 'active' : '', num(x.open_interest.total_notional) > 0 ? '' : 'inactive'].join(' ').trim() || null, title: num(x.open_interest.total_notional) > 0 ? null : 'No open positions' }, x.symbol)));
  const blockTimeMs = num(m.snapshot_block_time_ms);
  const hoursAgo = eventBlock => { const delta = num(m.snapshot_block) - num(eventBlock); return blockTimeMs && delta !== null ? delta * blockTimeMs / 3600000 : null; };
  const ladder = m.ladder;
  const ladderChart = columnChart({ width: chartWidth(2), categories: ladder.map(r => `${r.shock_pct}%`), series: [{ name: 'Longs liquidated (price falls)', color: c.long, values: ladder.map(r => num(r.long.notional)) }, { name: 'Shorts liquidated (price rises)', color: c.short, values: ladder.map(r => num(r.short.notional)) }], formatValue: (v, axis) => axis ? fmt.usd(v, 0) : fmt.usdFull(v), tooltipRows: i => { const r = ladder[i]; return [{ color: c.long, name: `Longs · ${r.long.count} at ${fmt.price(r.long.price, m.price_decimals)}`, value: fmt.usdFull(r.long.notional) }, { color: c.short, name: `Shorts · ${r.short.count} at ${fmt.price(r.short.price, m.price_decimals)}`, value: fmt.usdFull(r.short.notional) }, { name: 'Shortfall if gapped', value: fmt.usdFull(r.total_shortfall) }, { name: 'Insurance coverage', value: r.insurance_coverage_pct === null ? 'n/a' : fmt.cover(r.insurance_coverage_pct) }]; } });
  const allBins = fillBins(m.liquidation_map);
  const bins = m.liquidation_map.bins;
  const zeroIndex = allBins.findIndex(b => b.from_pct >= 0);
  const mapChart = columnChart({ width: chartWidth(2), categories: allBins.map(b => `${b.from_pct}%`), series: [{ name: 'Long liquidation levels', color: c.long, values: allBins.map(b => num(b.long_notional)) }, { name: 'Short liquidation levels', color: c.short, values: allBins.map(b => num(b.short_notional)) }], formatValue: (v, axis) => axis ? fmt.usd(v, 0) : fmt.usdFull(v), xTickEvery: 10, marker: zeroIndex, tooltipRows: i => { const b = allBins[i]; const mark = num(m.prices.mark); return [{ name: 'Price range', value: `${fmt.price(mark * (1 + b.from_pct / 100), m.price_decimals)} – ${fmt.price(mark * (1 + b.to_pct / 100), m.price_decimals)}` }, { color: c.long, name: 'Longs', value: fmt.usdFull(b.long_notional) }, { color: c.short, name: 'Shorts', value: fmt.usdFull(b.short_notional) }, { name: 'Positions', value: String(b.count) }]; } });
  const health = m.health;
  const healthChart = columnChart({ width: chartWidth(2), yLabel: 'notional by health (%)', categories: health.map(b => b.to_pct === null ? `>${b.from_pct}` : b.from_pct === 0 ? `<${b.to_pct}` : `${b.from_pct}–${b.to_pct}`), series: [{ name: 'Notional', color: c.blue, values: health.map(b => num(b.notional)) }], formatValue: (v, axis) => axis ? fmt.usd(v, 0) : fmt.usdFull(v), tooltipRows: i => [{ name: 'Notional', value: fmt.usdFull(health[i].notional) }, { name: 'Positions', value: String(health[i].count) }] });
  const funding = m.funding_history;
  const intervalSec = num(m.funding.interval_seconds);
  const fundingChart = lineChart({ width: chartWidth(2), signed: true, series: [{ name: 'Rate', points: funding.map(f => ({ y: num(f.rate_pct), f })) }], formatValue: (v, axis) => axis ? `${v.toFixed(3)}%` : fmt.signedPct(v, 4), labelOf: p => { const ago = hoursAgo(p.f.funding_event_block); return ago === null ? `#${fmt.int(p.f.funding_event_block)}` : ago < 1 ? `${Math.round(ago * 60)} min ago` : `${ago.toFixed(1)} h ago`; }, rowsOf: i => { const f = funding[i]; return [{ name: 'Event block', value: fmt.int(f.funding_event_block) }, { name: 'Rate per interval', value: fmt.signedPct(f.rate_pct, 4) }, { name: '8h equivalent', value: intervalSec ? fmt.signedPct(num(f.rate_pct) * (28800 / intervalSec), 4) : '—' }, { name: 'Funding price', value: fmt.price(f.funding_price, m.price_decimals) }, { name: 'Payment per unit', value: f.payment_per_unit }, { name: 'Funding sum', value: f.funding_sum }]; } });
  const positions = m.top_positions;
  const ref = m.reference;
  const refText = ref && ref.found ? `Perpl API: mark Δ ${ref.markDeltaBps === null ? '—' : `${ref.markDeltaBps} bps`} · OI Δ ${ref.oiDeltaBps === null ? '—' : `${ref.oiDeltaBps} bps`} · margins ${ref.marginFractionsMatch ? 'match' : 'differ'} · funding ${ref.fundingRateMatch === null ? '—' : ref.fundingRateMatch ? 'match' : 'differ'}` : ref === null ? 'Perpl API cross-check disabled' : 'Market not listed by the Perpl API';
  const next = m.funding.next_announced;
  const points = series?.points ?? [];
  const L = m.liquidity;
  return h('div', {},
    nav,
    h('h1', {}, `${m.symbol} · ${m.name}`),
    h('p', { class: 'sub' }, `Mark ${fmt.price(m.prices.mark, m.price_decimals)} · oracle ${fmt.price(m.prices.oracle, m.price_decimals)} (basis ${fmt.signedPct(m.prices.basis_pct, 2)}) · max leverage ${fmt.lev(m.margin.max_leverage)} · maintenance ${fmt.pct(m.margin.maintenance_margin_pct, 2)} · ${m.active ? 'active' : `status ${m.status}`}${m.prices.mark_stale ? ' · mark price stale' : ''}${L ? ` · best bid ${fmt.price(L.best_bid, m.price_decimals)} / ask ${fmt.price(L.best_ask, m.price_decimals)}` : ''}`),
    h('div', { class: 'tiles' },
      tile('Open interest', fmt.usd(m.open_interest.total_notional), `${fmt.size(m.open_interest.long_size)} ${m.symbol} each side · ${m.open_interest.utilisation_pct === null ? '' : `${fmt.pct(m.open_interest.utilisation_pct, 1)} of cap`}`, null, sparkline(seriesOf(points, 'notional'))),
      tile('Positions', `${m.positions.count}`, `${m.positions.long} long · ${m.positions.short} short`),
      tile('Within 10% of liquidation', fmt.usd(m.risk.notional_at_10pct), `${fmt.usd(m.risk.long_notional_at_10pct)} longs · ${fmt.usd(m.risk.short_notional_at_10pct)} shorts`, null, sparkline(seriesOf(points, 'at_10pct'))),
      tile('Shortfall at 10%', fmt.usd(m.risk.shortfall_at_10pct), m.risk.insurance_coverage_at_10pct === null ? 'none beyond bankruptcy' : `insurance covers ${fmt.cover(m.risk.insurance_coverage_at_10pct)}`, m.risk.insurance_coverage_at_10pct === null || m.risk.insurance_coverage_at_10pct >= 100 ? 'good' : 'critical'),
      tile('Liquidity cover at 5%', L && L.cover_at_5pct ? fmt.cover(L.cover_at_5pct.min_pct) : '—', L && L.cover_at_5pct ? `longs ${fmt.cover(L.cover_at_5pct.long_pct)} · shorts ${fmt.cover(L.cover_at_5pct.short_pct)} of liquidation flow absorbed by resting orders` : 'book not read yet', L && L.cover_at_5pct && L.cover_at_5pct.min_pct !== null && L.cover_at_5pct.min_pct < 100 ? 'critical' : null),
      tile('Insurance fund', fmt.usd(m.insurance.balance), `${fmt.pct(m.insurance.coverage_of_maintenance_pct, 0)} of maintenance margin`, null, sparkline(seriesOf(points, 'insurance'))),
      tile('Funding (8h eq.)', fmt.signedPct(m.funding.rate_8h_pct, 4), `${m.funding.direction} · next in ${fmt.duration(m.funding.seconds_to_next)}${next ? ` at ${fmt.signedPct(next.rate_pct, 4)} (set on-chain)` : ''} · ${fmt.signedPct(m.funding.rate_annualized_pct, 1)} annualised`),
      tile('Liquidatable now', `${m.positions.liquidatable}`, m.positions.bankrupt ? `${m.positions.bankrupt} bankrupt` : 'at or below maintenance', m.positions.liquidatable ? 'critical' : 'good'),
      tile('Top position', fmt.pct(m.concentration.top1_pct, 1), `of open interest · top 5 ${fmt.pct(m.concentration.top5_pct, 1)} · HHI ${fmt.int(m.concentration.hhi)}`)),
    h('div', { class: 'grid wide' }, stressCard(m)),
    h('div', { class: 'grid' },
      card('Liquidation ladder', 'Cumulative notional liquidated as the mark moves against each side; shortfall is the equity below zero if the move gaps past bankruptcy.', legend([{ name: 'Longs (price falls)', color: c.long }, { name: 'Shorts (price rises)', color: c.short }]), ladderChart, tableView('Show data table', ['Move', 'Long price', 'Longs', 'Short price', 'Shorts', 'Shortfall', 'Coverage'], ladder.map(r => [`${r.shock_pct}%`, fmt.price(r.long.price, m.price_decimals), `${fmt.usdFull(r.long.notional)} (${r.long.count})`, fmt.price(r.short.price, m.price_decimals), `${fmt.usdFull(r.short.notional)} (${r.short.count})`, fmt.usdFull(r.total_shortfall), r.insurance_coverage_pct === null ? '—' : fmt.cover(r.insurance_coverage_pct)]))),
      card('Liquidation map', `Liquidation prices binned every ${m.liquidation_map.bin_pct}% around the mark. Beyond ±${m.liquidation_map.range_pct}%: ${m.liquidation_map.tails.below.count} longs (${fmt.usd(m.liquidation_map.tails.below.notional)}), ${m.liquidation_map.tails.above.count} shorts (${fmt.usd(m.liquidation_map.tails.above.notional)}).`, legend([{ name: 'Long liquidation levels', color: c.long }, { name: 'Short liquidation levels', color: c.short }]), mapChart, tableView('Show data table', ['From', 'To', 'Longs', 'Shorts', 'Positions'], bins.map(b => [`${b.from_pct}%`, `${b.to_pct}%`, fmt.usdFull(b.long_notional), fmt.usdFull(b.short_notional), String(b.count)])))),
    h('div', { class: 'grid' }, ...liquidityCards(m)),
    h('div', { class: 'grid' },
      card('Funding rate history', `Rate applied per funding interval (${fmt.duration(intervalSec)}), from FundingEventCompleted events. Positive means longs pay shorts.`, funding.length ? fundingChart : h('div', { class: 'empty' }, 'No funding events collected yet'), tableView('Show data table', ['Event block', 'Rate', 'Funding price', 'Payment per unit', 'Funding sum'], funding.slice().reverse().map(f => [fmt.int(f.funding_event_block), fmt.signedPct(f.rate_pct, 4), fmt.price(f.funding_price, m.price_decimals), f.payment_per_unit, f.funding_sum]))),
      card('Position health', 'Equity as a share of maintenance margin. Below 100% is liquidatable.', healthChart, tableView('Show data table', ['Health', 'Positions', 'Notional'], health.map(b => [b.to_pct === null ? `> ${b.from_pct}%` : `${b.from_pct}–${b.to_pct}%`, String(b.count), fmt.usdFull(b.notional)])))),
    h('div', { class: 'grid wide' }, adlCard(m)),
    h('div', { class: 'grid wide' },
      cardWithActions('Positions', refText, [h('a', { href: `${API}/markets/${m.id}/positions?format=csv&sort=${view.sort}&limit=1000`, download: '' }, 'Download CSV')], h('div', { class: 'controls' }, h('label', { for: 'sort' }, 'Sort by'), h('select', { id: 'sort', onchange: evt => { view.sort = evt.target.value; app.refresh(); } }, ['notional', 'risk', 'pnl', 'size'].map(x => h('option', { value: x, selected: view.sort === x ? 'selected' : null }, { notional: 'Notional', risk: 'Closest to liquidation', pnl: 'Unrealised PnL', size: 'Size' }[x]))), h('span', {}, `showing ${positions.length} of ${m.positions.count}`)),
        table(['Account', 'Side', 'Size', 'Notional', 'Entry', 'Liq. price', 'Distance', 'Leverage', 'Health', 'PnL'], positions.map(p => h('tr', {}, h('td', { class: 'left mono' }, h('a', { href: `#/account/${p.account_id}` }, `#${p.account_id}`)), h('td', { class: 'left' }, h('span', { class: `side-${p.side}` }, p.side)), h('td', {}, fmt.size(p.size)), h('td', {}, fmt.usd(p.notional)), h('td', {}, fmt.price(p.entry_price, m.price_decimals)), h('td', {}, num(p.liquidation_price) > 0 ? fmt.price(p.liquidation_price, m.price_decimals) : '—'), h('td', { class: p.status !== 'healthy' ? 'status-bad' : num(p.liquidation_distance_pct) < 5 ? 'status-warn' : null }, p.status !== 'healthy' ? p.status : fmt.pct(p.liquidation_distance_pct, 1)), h('td', {}, fmt.lev(p.leverage)), h('td', {}, fmt.pct(p.health_pct, 0)), h('td', { class: num(p.pnl) < 0 ? 'status-bad' : 'status-ok' }, fmt.usd(p.pnl)))), 2)),
      card('Recent liquidations', m.recent_liquidations.length ? 'From PositionLiquidated events collected since the collector started.' : null, m.recent_liquidations.length ? liquidationTable(m.recent_liquidations, false) : h('div', { class: 'empty' }, 'No liquidations in the collected range'))));
}
export function fillBins(map) {
  const step = num(map.bin_pct), range = num(map.range_pct), byFrom = new Map(map.bins.map(b => [Number(b.from_pct).toFixed(2), b]));
  const out = [];
  for (let from = -range; from < range - 1e-9; from += step) { const key = from.toFixed(2); out.push(byFrom.get(key) ?? { from_pct: Number(key), to_pct: Number((from + step).toFixed(2)), count: 0, long_notional: '0', short_notional: '0' }); }
  return out;
}
export function liquidationTable(rows, withMarket = true) {
  return table([...(withMarket ? ['Market'] : []), 'Block', 'Account', 'Side', 'Size', 'Notional', 'Exit price', 'Mark', 'Type', 'Tx'],
    rows.map(l => h('tr', {}, withMarket ? h('td', { class: 'left' }, h('strong', {}, l.symbol ?? `#${l.market_id}`)) : null, h('td', { class: 'left mono' }, fmt.int(l.block)), h('td', { class: 'left mono' }, h('a', { href: `#/account/${l.account_id}` }, `#${l.account_id}`)), h('td', { class: 'left' }, h('span', { class: `side-${l.side}` }, l.side)), h('td', {}, fmt.size(l.liquidated_size)), h('td', {}, fmt.usd(l.liquidated_notional)), h('td', {}, fmt.price(l.exit_price)), h('td', {}, fmt.price(l.mark_price)), h('td', {}, l.full ? 'full' : 'partial'), h('td', {}, h('a', { href: `https://monadscan.com/tx/${l.tx}`, target: '_blank', rel: 'noopener', class: 'mono' }, fmt.short(l.tx))))), withMarket ? 4 : 3);
}
export function validationView(v, r, idx = null) {
  const ver = v.verification;
  const items = Object.entries(v.metrics);
  const bf = idx?.backfill ?? null;
  const indexCard = idx ? card('Event index', 'Trades, fills, flows and account creations decoded from exchange events; hourly aggregates outlive the raw window.', h('dl', { class: 'kv' }, h('dt', {}, 'Records'), h('dd', {}, fmt.int(idx.records)), h('dt', {}, 'Accounts seen'), h('dd', {}, fmt.int(idx.accounts)), h('dt', {}, 'Covered since'), h('dd', {}, idx.covered_from_ts ? `${new Date(idx.covered_from_ts * 1000).toLocaleString('en-GB')} (block ${fmt.int(idx.covered_from_block)})` : '—'), h('dt', {}, 'Hourly buckets'), h('dd', {}, fmt.int(idx.buckets)), h('dt', {}, 'OI snapshots'), h('dd', {}, fmt.int(idx.snapshots)), h('dt', {}, 'Backfill'), h('dd', {}, bf ? (bf.running ? `running · reached block ${fmt.int(bf.reached_block)}` : bf.complete ? 'complete' : bf.error === 'HORIZON' ? `stopped at the RPC history horizon (block ${fmt.int(bf.reached_block)})` : bf.error ?? 'idle') : '—'), h('dt', {}, 'Raw window'), h('dd', {}, `${fmt.int(idx.window_blocks)} blocks`))) : null;
  const venueRows = r.enabled ? r.markets.filter(x => x.comparison && x.comparison.found && x.comparison.reference?.dailyVolume) : [];
  return h('div', {}, h('h1', {}, 'Validation'), h('p', { class: 'sub' }, 'What the collector checks continuously, and how each metric was validated against the contract.'),
    indexCard ? h('div', { class: 'grid' }, indexCard, card('Venue-reported 24h volume', 'Perpl\'s public API reports a rolling 24h volume per market (dva). The chain figure is the sum of maker fills over the same window; both should agree within the window alignment.', venueRows.length ? table(['Market', 'Perpl API', 'Chain (24h)', 'Δ'], venueRows.map(x => { const ref = Number(x.comparison.reference.dailyVolume) / 1e6; const chain = Number(x.chain_volume_24h ?? NaN); return h('tr', {}, h('td', { class: 'left' }, x.symbol), h('td', {}, fmt.usd(ref)), h('td', {}, Number.isFinite(chain) ? fmt.usd(chain) : '—'), h('td', { class: Number.isFinite(chain) && Math.abs(chain / ref - 1) < 0.01 ? 'status-ok' : 'status-warn' }, Number.isFinite(chain) && ref > 0 ? fmt.signedPct((chain / ref - 1) * 100, 2) : '—')); })) : h('div', { class: 'empty' }, 'Reference data not available'))) : null,
    h('div', { class: 'grid' },
      card('Snapshot', null, h('dl', { class: 'kv' }, h('dt', {}, 'Block'), h('dd', {}, fmt.int(v.snapshot.block)), h('dt', {}, 'Hash'), h('dd', { class: 'mono' }, fmt.short(v.snapshot.block_hash)), h('dt', {}, 'Finalized'), h('dd', {}, fmt.int(v.snapshot.finalized_block)), h('dt', {}, 'Status'), h('dd', {}, v.snapshot.status), h('dt', {}, 'Bootstrap'), h('dd', {}, v.bootstrap ? `block ${fmt.int(v.bootstrap.block)} (${v.bootstrap.reason})` : '—'), h('dt', {}, 'Polls'), h('dd', {}, fmt.int(v.collector.polls)), h('dt', {}, 'RPC requests'), h('dd', {}, fmt.int(v.rpc.requests)), h('dt', {}, 'Errors'), h('dd', {}, fmt.int(v.collector.errors)))),
      card('Open-interest reconciliation', 'Every poll: stored positions summed per side must equal the contract counters at the same block.', v.reconciliation ? h('div', {}, statusPill(v.reconciliation.ok, `exact at block ${fmt.int(v.reconciliation.block)}`, `mismatch at block ${fmt.int(v.reconciliation.block)}`), h('p', { class: 'tile-note' }, `${v.reconciliation.markets} markets checked · ${fmt.ago(Date.now() - v.reconciliation.at)} ago`)) : h('div', { class: 'empty' }, 'Not yet run')),
      card('Independent discovery', 'Periodic rescan of every account through position bitmaps, compared with the stored positions.', ver ? h('div', {}, ver.ok === null ? h('span', { class: 'pill' }, `error: ${ver.error}`) : statusPill(ver.ok, `agrees at block ${fmt.int(ver.block)}`, `mismatch at block ${fmt.int(ver.block)}`), h('p', { class: 'tile-note' }, ver.ok === null ? '' : `${fmt.int(ver.accounts)} accounts · ${ver.candidates} candidates · ${ver.scanned} positions · ${ver.requests} requests · ${fmt.ago(ver.ms)}`)) : h('div', { class: 'empty' }, 'Scheduled after bootstrap')),
      card('PnL agreement', 'Delta PnL recomputed from entry, size and mark, compared with the contract for every position read since start.', table(['Market', 'Checked', 'Agree'], v.pnl_agreement.map(x => h('tr', {}, h('td', { class: 'left' }, x.symbol), h('td', {}, x.checked), h('td', { class: x.agree === x.checked ? 'status-ok' : 'status-bad' }, x.agree)))))),
    h('div', { class: 'grid wide' },
      card('Cross-check against the Perpl API', 'Reference only. The public context endpoint is compared with the contract state; it never feeds a metric.', r.enabled ? table(['Market', 'Mark Δ (bps)', 'OI Δ (bps)', 'Margins', 'Funding rate', 'Funding sum', 'Reference block'], r.markets.map(x => { const c = x.comparison; return h('tr', {}, h('td', { class: 'left' }, x.symbol), ...(c && c.found ? [h('td', {}, c.markDeltaBps ?? '—'), h('td', {}, c.oiDeltaBps ?? '—'), h('td', { class: c.marginFractionsMatch ? 'status-ok' : 'status-bad' }, c.marginFractionsMatch ? 'match' : 'differ'), h('td', { class: c.fundingRateMatch === false ? 'status-bad' : 'status-ok' }, c.fundingRateMatch === null ? '—' : c.fundingRateMatch ? 'match' : 'differ'), h('td', { class: c.fundingSumMatch === false ? 'status-bad' : 'status-ok' }, c.fundingSumMatch === null ? '—' : c.fundingSumMatch ? 'match' : 'differ'), h('td', {}, fmt.int(c.referenceBlock))] : [h('td', { colspan: 6, style: 'text-align:left;color:var(--muted)' }, 'not listed by the API')])); })) : h('div', { class: 'empty' }, 'Cross-check disabled')),
      card('Metric status', null, table(['Metric', 'Status', 'Method'], items.map(([name, x]) => h('tr', {}, h('td', { class: 'left' }, name.replace(/_/g, ' ')), h('td', { class: 'left' }, h('span', { class: 'pill' }, x.status)), h('td', { class: 'left', style: 'white-space:normal;min-width:320px' }, x.method))), 3))));
}
export function aboutView() {
  return h('div', { class: 'prose' }, h('h1', {}, 'About PerplScope'),
    h('p', {}, 'PerplScope is an independent analytics and risk monitor for the Perpl perpetual exchange on Monad. It reads the exchange contract directly, pins every read to one block, and recomputes open interest, unrealised PnL, liquidation prices, liquidation exposure, on-chain liquidity, funding and insurance coverage from that state. Volume, fees, flows, liquidations and every wallet\'s history come from the exchange events, summed exactly with the price of the fill that settled each position change. Nothing is taken on trust from the venue; Perpl\'s public API appears only as a cross-check.'),
    h('h2', {}, 'How the numbers are produced'),
    h('ul', {}, h('li', {}, 'Positions come from the contract\'s paged getter at a pinned block, then every block\'s exchange events name the positions to re-read. Positions are never derived from events.'), h('li', {}, 'Each poll sums the stored positions per side and compares them with the contract\'s own open-interest counters at the same block. Any difference forces a fresh snapshot.'), h('li', {}, 'Periodically every account is rescanned through its position bitmaps, an enumeration path independent of the paged getter.'), h('li', {}, 'Resting order-book depth is walked level by level from the contract at the same block, so liquidation demand can be compared with the liquidity that would absorb it.'), h('li', {}, 'Delta PnL is recomputed and compared with the contract for every position read.')),
    h('h2', {}, 'Formulas'),
    h('p', {}, 'From the Perpl documentation and the open-source SDK. Maintenance margin requirement ', h('code', {}, 'MMR = entry × size ÷ maintenance fraction'), '. Liquidation price ', h('code', {}, 'P = entry + side × (MMR − deposit − premium PnL) ÷ size'), '. Bankruptcy price ', h('code', {}, 'P = entry − side × (deposit + premium PnL) ÷ size'), '. Equity ', h('code', {}, 'FMV = deposit + delta PnL + premium PnL'), '; a position is liquidatable when ', h('code', {}, '0 < FMV ≤ MMR'), '.'),
    h('p', {}, 'The liquidation ladder counts positions whose liquidation price lies within each adverse move of the mark. Shortfall is the equity below zero that would remain if the move gapped past bankruptcy before a liquidation executed; insurance coverage divides the market\'s insurance balance by that shortfall. Liquidity cover divides the firm resting depth within the same move by the liquidation notional that would have to trade through it.'),
    h('h2', {}, 'Activity and wallet metrics'),
    h('p', {}, 'Volume is the sum of maker-fill notional, so each match counts once; fees are the maker and taker fill fees, which Perpl charges only on fills that build a position, and their insurance and protocol split comes from the position events. Active traders are distinct accounts with a fill or position change. Realized PnL is the contract\'s delta PnL plus funding on reducing, closing, inverting, liquidated and deleveraged events. A wallet\'s round trips group its position changes per market and side; win rate, profit factor, drawdown, streaks and hold times are computed over closed trips. Every window says whether it is an exact sum, an hourly aggregate, or partial.'),
    h('h2', {}, 'Limits'),
    h('ul', {}, h('li', {}, 'Isolated-margin positions only, as deployed. Depth walks are bounded per side and note when truncated.'), h('li', {}, 'The liquidation price uses the current maintenance fraction and the contract\'s current premium PnL; funding accrued between funding events is not projected.'), h('li', {}, 'Wallet history and windowed metrics reach as far back as the RPC provider\'s log history and the configured window; hourly aggregates persist across restarts so longer windows fill in over time.')),
    h('p', {}, h('a', { href: 'https://github.com/s0urledd/perpl-scope' }, 'Source, methodology and validation evidence on GitHub'), '.'));
}

